### ISSUE TITLE
Issue with the calendar plugin

### ISSUE THREAD

**Issue by RikardSwed** [jemstelos/obsidian-media-notes#14]
When I enable "media Note" the arrows in the calendar plugin that switches month dissapears.

**Comment by Blueasharky** [comment]
I'm having the same issue, with [this calendar plugin](https://github.com/liamcain/obsidian-calendar-plugin).
I installed both the calendar plugin and the media notes plugin in a sandbox vault and enabled both which caused the calendar arrows to merge into the one.
![image](https://github.com/jemstelos/obsidian-media-notes/assets/17265022/ff3baf89-9d64-40a2-91f8-f16b0a84995a)
![image](https://github.com/jemstelos/obsidian-media-notes/assets/17265022/7b3dbcdf-59cf-4263-90a7-0f5617021219)

**Comment by jemstelos** [comment]
looks like this was a style conflict - will fix in the next release!

**Comment by RikardSwed** [comment]
Great, thanks! Appreciate your work.

**Comment by Astro1963** [comment]
> When I enable "media Note" the arrows in the calendar plugin that switches month dissapears.

Yes, the same thing happens to me too!

**Comment by jemstelos** [comment]
This should have been resolved with https://github.com/jemstelos/obsidian-media-notes/commit/aa89563a656dedbcdaaefa53a2539f6e7013a1ba. The issue was that the `.arrow` css class was being used across both plugins. Please re-open if you see it reoccur with the latest version.
