### ISSUE TITLE
Plugin brokes calendar plugin navigation

### ISSUE THREAD

**Issue by DaudKadirov** [jemstelos/obsidian-media-notes#19]
![image](https://github.com/user-attachments/assets/540c9005-1ea5-49a5-b2a8-c42a2635cd22)
![image](https://github.com/user-attachments/assets/a0b3f9e1-6f87-43b1-bf6a-270d8e74cb42)

Hello i have this issue! The calendar plugin navigation is brokes if your plugin is active! Please fix it

**Comment by jemstelos** [comment]
This should have been resolved with https://github.com/jemstelos/obsidian-media-notes/commit/aa89563a656dedbcdaaefa53a2539f6e7013a1ba. The issue was that the `.arrow` css class was being used across both plugins. Please re-open if you see it reoccur with the latest version.
