### ISSUE TITLE
Not all YouTube title is accepted as note title

### ISSUE THREAD

**Issue by glitchlover** [jemstelos/obsidian-media-notes#3]
In obsidian there are some character like `<>()/\|*?` are not accepted as file title. But in youtube some video title contains this character. As a result the media note link fails to create notes for youtube.

**Comment by jemstelos** [comment]
just to confirm - <>()*? all work in obsidian.
we already do regex replace for ()/\:
|  replace was not implemented - thanks for flagging. will address

**Comment by jemstelos** [comment]
https://github.com/jemstelos/obsidian-media-notes/commit/d84a30f21f75cb1d17903cf0c5849ff61320be43
addressed here - you'll need to update the bookmarklet to v 1.2 for the fix
