### ISSUE TITLE
Video stops playing when typing

### ISSUE THREAD

**Issue by MrSweezy** [jemstelos/obsidian-media-notes#30]
The Video stops playing when i'm typing.

**Comment by Aaqil101** [comment]
You can turn it off in the plugins option menu.

![image](https://github.com/user-attachments/assets/c14e5278-8d02-4d82-b86a-8ed653589553)

**Comment by jemstelos** [comment]
Thank you @Aaqil101. You can have the video stop playing whenever you add a timestamp.
If the video player is selected, then normal YouTube shortcuts apply (e.g spacebar will play/pause the video).

**Comment by Aaqil101** [comment]
You are Welcome. I didn't know that thanks😊
