### ISSUE TITLE
Enable pause automatically.

### ISSUE THREAD

**Issue by n30s4m** [jemstelos/obsidian-media-notes#4]
Enable the option to automatically pause the video when the timestamp is inserted, this way there will be the possibility of a calmer annotation and the video can be played again later, with manual play or some other way.

VLC Bridge Plugin have this option.
Another option is to insert a screenshot of the video with a single command.

**Comment by jemstelos** [comment]
https://github.com/jemstelos/obsidian-media-notes/commit/d84a30f21f75cb1d17903cf0c5849ff61320be43
Addressed here, will be available in 1.2.0 release
